### ISSUE TITLE
<meta name="ROBOTS" content="NOINDEX, NOFOLLOW">

### ISSUE THREAD

**Issue by martinvirtel** [dpa-newslab/liveblog-theme-dpa#48]
Siehe http://www.robotstxt.org/meta.html

denn: 

![image](https://cloud.githubusercontent.com/assets/9485782/16896577/b61261d2-4b98-11e6-9af7-f99d4513683c.png)

**Comment by psnewslab** [comment]
Ist jetzt als feld `blockSearchEngines` in den theme settings in der `theme.json` verfügbar.    
Wird mit dem nächsten theme update deploy't.

https://github.com/liveblog/liveblog/blob/63e1fd508dd04b6eee8892f063162a645c6f657d/server/liveblog/embed/templates/embed.html#L8
